name: servicehubpeople
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  mongo_dart: ^0.9.3
  flutter_dotenv: ^5.1.0
  http: ^1.3.0
  shared_preferences: ^2.2.0 # Added for API requests

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
